---

- name: Get config file
  command: cat {{ config_file_name }}
  check_mode: no
  register: config_file_output

- name: Create map from string
  set_fact:
    config_file_map: "{{ dict(_keys|zip(_vals)) }}"
  vars:
    _arr: "{{ config_file_output.stdout.split('\n')|map('trim')|select()|list }}"
    _keys: "{{ _arr|map('regex_replace', '^(.*?)=(.*)$', '\\1')|map('trim')|list }}"
    _vals: "{{ _arr|map('regex_replace', '^(.*?)=(.*)$', '\\2')|map('trim')|list }}"
  failed_when: config_file_map.ADDRESS is undefined or config_file_map.RESULT_ADDRESS is undefined or config_file_map.PRIVATE_KEY is undefined or config_file_map.RESULT_PRIVATE_KEY is undefined

- name: Defining node address request
  uri:
    url: https://bloxberg.ethernity.cloud
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body: '{"method":"eth_getBalance","params":["{{ config_file_map.ADDRESS }}","latest"],"id":1,"jsonrpc":"2.0"}'
  register: addressbergs
  retries: 64
  delay: 3

- name: Defining result address request
  uri:
    url: https://bloxberg.ethernity.cloud
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body: '{"method":"eth_getBalance","params":["{{ config_file_map.RESULT_ADDRESS }}","latest"],"id":1,"jsonrpc":"2.0"}'
  register: resultbergs
  retries: 64
  delay: 3

- name: Comparing ADDRESS with RESULT ADDRESS
  debug:
    msg: "Result address must be different than node address."
  failed_when: config_file_map.ADDRESS == config_file_map.RESULT_ADDRESS

- name: Comparing PRIVATE KEY with RESULT PRIVATE KEY
  debug:
    msg: "Result private key must be different than node private key."
  failed_when: config_file_map.PRIVATE_KEY == config_file_map.RESULT_PRIVATE_KEY

- name: Evaluate ADDRESS message
  debug:
    msg: "{{ addressbergs.json }}"
  failed_when: addressbergs.json == ""

- name: Evaluate RESULT ADDRESS message
  debug:
    msg: "{{ resultbergs.json }}"
  failed_when: resultbergs.json == ""


- name: Get Node ADDRESS balance
  debug:
    msg:
      - "Node ADDRESS balance: '{{ addressbergs.json.result|int}}' bergs."
      - "Please get bergs on {{ config_file_map.ADDRESS }} from https://faucet.bloxberg.org/ and try again."
  failed_when:
    - addressbergs.json.result|int == 0
  when:
    - addressbergs.json.result is defined
    - addressbergs.json.result == '0x0'

- name: Get RESULT ADDRESS balance
  debug:
    msg:
      - "Node RESULT ADDRESS balance: '{{ resultbergs.json.result|int}}' bergs."
      - "Please get bergs on {{ config_file_map.RESULT_ADDRESS }} from https://faucet.bloxberg.org/ and try again."
  failed_when:
    - resultbergs.json.result|int == 0
  when:
    - resultbergs.json.result is defined
    - resultbergs.json.result == '0x0'

- meta: end_play
  when: (resultbergs.json.result is defined and resultbergs.json.result == '0') or (addressbergs.json.result is defined and addressbergs.json.result == '0') or (config_file_map.PRIVATE_KEY == config_file_map.RESULT_PRIVATE_KEY) or (config_file_map.ADDRESS == config_file_map.RESULT_ADDRESS)
